#define OS_WINNT	1
#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE	_
#define NEEDBUNDERSCORE	1
#define SKYLAKEX
#define L1_DATA_SIZE 32768
#define L1_DATA_LINESIZE 64
#define L2_SIZE 262144
#define L2_LINESIZE 64
#define DTB_DEFAULT_ENTRIES 64
#define DTB_SIZE 4096
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_AVX
#define FMA3
#define HAVE_AVX512VL
#define CORE_SKYLAKEX
#define CHAR_CORENAME "SKYLAKEX"
#define SLOCAL_BUFFER_SIZE	20480
#define DLOCAL_BUFFER_SIZE	12288
#define CLOCAL_BUFFER_SIZE	12288
#define ZLOCAL_BUFFER_SIZE	8192
#define GEMM_MULTITHREAD_THRESHOLD	4
